### ISSUE TITLE
Emergent mode fails with `AttributeError: 'str' object has no attribute 'isocalendar'`

### ISSUE THREAD

**Issue by pjlegato** [datasciencecampus/pyGrams#227]
**Describe the bug**
When running with `-emt`, CSV input, and a date field given in the required format `YYYY/MM/DD`, it crashes with:

```
  File "/Users/paul/src/pyGrams/scripts/tfidf_reduce.py", line 77, in <listcomp>
    [d.isocalendar() for d in dates]]
AttributeError: 'str' object has no attribute 'isocalendar'
```

The code does not appear to be parsing the input date string as a date object; it attempts to call date methods on a string.

**To Reproduce**
1. Create a CSV input file with a date field in YYYY/MM/DD format
2. Run `python pygrams.py -emt -ds=posts.csv -dh='date' -th text > emergent.out`
3. Crashes with above error

**Expected behavior**
Should not crash; should calculate emerging terms.

**Desktop (please complete the following information):**
 - OS: Mac OS 
 -  Python 3.7.2

**Comment by thanasions** [comment]
Thanks for raising the issue. We are currently looking into this!

**Comment by IanGrimstead** [comment]
Created branch `227-bug-csv-date`

**Comment by IanGrimstead** [comment]
3.7.3 running under Xenial linux dist; appveyor should be ok (worked with 3.7) - awaiting build...
So we should be fine with >3.7

**Comment by thanasions** [comment]
bug is fixed on brunch develop now.

**Comment by IanGrimstead** [comment]
Thanks for reporting the issue - a new build has been pushed to develop and master, so should now be fixed. Anything else not working, please raise it & we'll take a look.
